apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: utb-devops-demo-hpa
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: utb-devops-demo
  targetCPUUtilizationPercentage: 50
